grails-app/domain/com/changeIT/Customer.groovy
package com.changeIT

class Customer {
    enum Gender {
        customerSexMale, customerSexFemale
    }
    String name
    String lastName
    String email
    String address
    String cuit
    String phone
    String razonSocial
    Double limiteCompra
    Date created = new Date()
    String gender
    SecUser secUser
    static hasMany = [orders: Orders]
    static constraints = {
        email email: true
        secUser(nullable:false)
        name(nullable:true)
        lastName(nullable:true)
        address(nullable:true)
        cuit(nullable:true)
        razonSocial(nullable:true)
        limiteCompra(nullable:true)
        gender(nullable:true)
    }

}

grails-app/controllers/com/changeIT/CustomerController.groovy
package com.changeIT

import com.changeIT.util.Base64URL
import com.changeIT.util.Util
import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class CustomerController {
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    CustomerService customerService
    SecUserCustomService secUserCustomService
    CorreoUtil correo = new CorreoUtil()
    Base64URL base64URL = new Base64URL()
    Util util = new Util()

    @Secured(['ROLE_ADMIN','ROLE_VENDEDOR'])
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond customerService.list(params), model: [customerCount: customerService.count()]
    }

    @Secured(['ROLE_ADMIN','ROLE_VENDEDOR'])
    def index2() {
        params.max = 10
        respond customerService.list(params), model: [customerCount: customerService.count()]
    }

    @Secured(['ROLE_ADMIN','ROLE_VENDEDOR', 'ROLE_CLIENTE'])
    def show(Long id) {
        respond customerService.get(id)
    }

    @Secured(['ROLE_ADMIN','ROLE_VENDEDOR'])
    def create() {
        respond new Customer(params)
    }

    @Secured(['ROLE_ADMIN','ROLE_VENDEDOR'])
    def save(Customer customer) {
        String MAIL_TEMPLATES = "mail"
        if (customer == null) {
            notFound()
            return
        }

        try {
            SecUser user = new SecUser(username: customer.email, password: params.passwordID, enabled: true, accountExpired: false, accountLocked: false, passwordExpired: false, name:  customer.getName(), lastName: customer.getLastName(), phone: customer.getPhone(), email: customer.getEmail(),attempts: 0)
            customer.secUser = user
            customer = secUserCustomService.saveUserCustomer(customer,SecRole.findByAuthority("ROLE_CLIENTE"))
        } catch (ValidationException e) {
            respond customer.errors, view: 'create'
            return
        }
        String text = util.getFile(MAIL_TEMPLATES + File.separator + "userPassInform.html")

        text = text.replace("[password]",  params.passwordID)
        text = text.replace("[email]", customer.email)
        text = text.replace("[title]", g.message(code: "mail.tarificador.title"))
        text = text.replace("[text]", g.message(code: "mail.user.create.text"))
        text = text.replace("[text2]", g.message(code: "mail.user.create.text2"))
        text = text.replace("[text3]", g.message(code: "mail.user.create.text3"))
        text = text.replace("[text4]", g.message(code: "mail.user.create.text4"))
        text = text.replace("[greeting]", g.message(code: "mail.greeting"))

        correo.sendMail(text, g.message(code: "mail.user.subject.update"), customer.email)
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'customer.label', default: 'Customer'), customer.id])
                redirect customer
            }
            '*' { respond customer, [status: CREATED] }
        }
    }

    @Secured(['ROLE_ADMIN','ROLE_VENDEDOR', 'ROLE_CLIENTE'])
    def edit(Long id) {
        respond customerService.get(id)
    }

    @Secured(['ROLE_ADMIN','ROLE_VENDEDOR', 'ROLE_CLIENTE'])
    def update(Customer customer) {
        if (customer == null) {
            notFound()
            return
        }

        try {
            customerService.save(customer)
        } catch (ValidationException e) {
            respond customer.errors, view: 'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'customer.label', default: 'Customer'), customer.id])
                redirect customer
            }
            '*' { respond customer, [status: OK] }
        }
    }

    @Secured(['ROLE_ADMIN'])
    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        customerService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'customer.label', default: 'Customer'), id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    @Secured(['ROLE_ADMIN','ROLE_VENDEDOR'])
    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'customer.label', default: 'Customer'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/customer/_form.gsp
<%@ page import="com.changeIT.Customer" %>
<div class="col-md-8 offset-md-2">
    <div
            class="fieldcontain row ${hasErrors(bean: customer, field: 'email', 'error')} required">
        <label for="email" class="col-md-6"><g:message code="customer.form.email" default="Email"/>
            <span class="required-indicator">*</span>
        </label>
        <g:textField name="email" class="col-md-6" required="" value="${customer?.email}"/>
    </div>

    <div
            class="fieldcontain row  ${hasErrors(bean: customer, field: 'name', 'error')} required">
        <label for="name" class="col-md-6"><g:message
                code="customer.form.name" default="Nom"/>
            <span class="required-indicator">*</span>
        </label>
        <g:textField name="name" class="col-md-6" required=""
                     value="${customer?.name}"/>
    </div>

    <div   class="fieldcontain row ${hasErrors(bean: customer, field: 'lastName', 'error')} required">
        <label for="lastName" class="col-md-6"><g:message
                code="customer.form.lastname" default="Prenom"/> <span
                class="required-indicator">*</span>
        </label>
        <g:textField name="lastName" class="col-md-6" required=""
                     value="${customer?.lastName}"/>
    </div>
    <div    class="fieldcontain row ${hasErrors(bean: customer, field: 'gender', 'error')} required">
        <label for="lastName" class="col-md-6"><g:message
                code="customer.form.gender" default="Genero"/> <span
                class="required-indicator">*</span>
        </label>
        <g:select name="gender"
                  value="${customer?.gender}"
                  from="[message(code: 'customerSexMale'), message(code: 'customerSexFemale')]" noSelection="['': message(code: 'customer.sex.gender')]"
                  optionKey=""
                  class="col-md-6"/>
    </div>


    <div
            class="fieldcontain row ${hasErrors(bean: customer, field: 'address', 'error')} required">
        <label for="address" class="col-md-6"><g:message
                code="customer.form.address"
                default="Adresse/ Code postal/ Ville"/>
            <span class="required-indicator">*</span>
        </label>
        <g:textArea class="col-md-6" name="address" required=""
                     value="${customer?.address}"/>
    </div>


    <div class="fieldcontain row ${hasErrors(bean: customer, field: 'cuit', 'error')} required">
        <label for="address" class="col-md-6"><g:message
                code="customer.form.cuit"
                default="cuit"/> <span
                class="required-indicator">*</span>
        </label>
        <g:textField class="col-md-6" name="cuit" required=""
                     value="${customer?.cuit}"/>
    </div>

    <div class="fieldcontain row ${hasErrors(bean: customer, field: 'razonSocial', 'error')} required">
        <label for="address" class="col-md-6"><g:message
                code="customer.form.razonSocial"
                default="razonSocial"/> <span
                class="required-indicator">*</span>
        </label>
        <g:textField class="col-md-6" name="razonSocial" required=""
                     value="${customer?.razonSocial}"/>
    </div>

    <div class="fieldcontain row ${hasErrors(bean: customer, field: 'phone', 'error')} required">
        <label for="address" class="col-md-6"><g:message
                code="customer.form.phone"
                default="Telefono"/> <span
                class="required-indicator">*</span>
        </label>
        <g:textField class="col-md-6" name="phone" required=""
                     value="${customer?.phone}"/>
    </div>

    <div class="fieldcontain row ${hasErrors(bean: customer, field: 'limiteCompra', 'error')} required">
        <label for="address" class="col-md-6"><g:message
                code="customer.form.limiteCompra"
                default="limiteCompra"/> <span
                class="required-indicator">*</span>
        </label>
        <g:textField class="col-md-6" name="limiteCompra" required=""
                     value="${customer?.limiteCompra}"/>
    </div>


</div>

grails-app/views/customer/_formEdition.gsp
<%@ page import="com.changeIT.Customer" %>
<div class="col-md-8 offset-md-2">
    <div
            class="fieldcontain row ${hasErrors(bean: customer, field: 'email', 'error')} required">
        <label for="email" class="col-md-6"><g:message code="customer.form.email" default="Email"/>
            <span class="required-indicator">*</span>
        </label>
        <g:textField name="email" class="col-md-6" required="" value="${customer?.email}"/>
    </div>

    <div
            class="fieldcontain row  ${hasErrors(bean: customer, field: 'name', 'error')} required">
        <label for="name" class="col-md-6"><g:message
                code="customer.form.name" default="Nom"/>
            <span class="required-indicator">*</span>
        </label>
        <g:textField name="name" class="col-md-6" required=""
                     value="${customer?.name}"/>
    </div>

    <div
            class="fieldcontain row ${hasErrors(bean: customer, field: 'lastName', 'error')} required">
        <label for="lastName" class="col-md-6"><g:message
                code="customer.form.lastname" default="Prenom"/> <span
                class="required-indicator">*</span>
        </label>
        <g:textField name="lastName" class="col-md-6" required=""
                     value="${customer?.lastName}"/>
    </div>
    <div    class="fieldcontain row ${hasErrors(bean: customer, field: 'gender', 'error')} required">
        <label for="lastName" class="col-md-6"><g:message
                code="customer.form.gender" default="Genero"/> <span
                class="required-indicator">*</span>
        </label>
        <g:select name="gender"
                  value="${customer?.gender}"
                  from="[message(code: 'customerSexMale'), message(code: 'customerSexFemale')]" noSelection="['customerSexMale': message(code: 'customer.sex.gender')]"
                  optionKey=""
                  class="col-md-6"/>
    </div>

    <div
            class="fieldcontain row ${hasErrors(bean: customer, field: 'address', 'error')} required">
        <label for="address" class="col-md-6"><g:message
                code="customer.form.address"
                default="Adresse/ Code postal/ Ville"/>
            <span class="required-indicator">*</span>
        </label>
        <g:textArea class="col-md-6" name="address" required=""
                    value="${customer?.address}"/>
    </div>


    <div class="fieldcontain row ${hasErrors(bean: customer, field: 'cuit', 'error')} required">
        <label for="address" class="col-md-6"><g:message
                code="customer.form.cuit"
                default="cuit"/> <span
                class="required-indicator">*</span>
        </label>
        <g:textField class="col-md-6" name="cuit" required=""
                     value="${customer?.cuit}"/>
    </div>

    <div class="fieldcontain row ${hasErrors(bean: customer, field: 'razonSocial', 'error')} required">
        <label for="address" class="col-md-6"><g:message
                code="customer.form.razonSocial"
                default="razonSocial"/> <span
                class="required-indicator">*</span>
        </label>
        <g:textField class="col-md-6" name="razonSocial" required=""
                     value="${customer?.razonSocial}"/>
    </div>

    <div class="fieldcontain row ${hasErrors(bean: customer, field: 'phone', 'error')} required">
        <label for="address" class="col-md-6"><g:message
                code="customer.form.phone"
                default="Telefono"/> <span
                class="required-indicator">*</span>
        </label>
        <g:textField class="col-md-6" name="phone" required=""
                     value="${customer?.phone}"/>
    </div>
    <sec:ifAnyGranted roles="ROLE_ADMIN,ROLE_VENDEDOR">
        <div class="fieldcontain row ${hasErrors(bean: customer, field: 'limiteCompra', 'error')} required">
            <label for="address" class="col-md-6"><g:message
                    code="customer.form.limiteCompra"
                    default="limiteCompra"/> <span
                    class="required-indicator">*</span>
            </label>
            <g:textField class="col-md-6" name="limiteCompra" required=""
                         value="${customer?.limiteCompra}"/>
        </div>
    </sec:ifAnyGranted>

</div>

grails-app/views/customer/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'customer.label', default: 'Customer')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<a href="#create-customer" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                 default="Skip to content&hellip;"/></a>

<g:render template="/layouts/nav"/>

<div id="create-customer" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.customer}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.customer}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form resource="${this.customer}" method="POST">
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>

        <div class="fieldcontain row ${hasErrors(bean: customer?.secUser, field: 'password', 'error')} required">
            <label for="password" class="col-md-6"><g:message
                    code="customer.form.password"
                    default="Password"/> <span
                    class="required-indicator">*</span>
            </label>
            <g:passwordField class="col-md-6" name="passwordID" required=""/>
        </div>


        <fieldset class="buttons">
            <g:submitButton name="create" class="save"
                            value="${message(code: 'default.button.create.label', default: 'Create')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/customer/edit.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'customer.label', default: 'Customer')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-customer" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                               default="Skip to content&hellip;"/></a>

<g:render template="/layouts/nav"/>

<div id="edit-customer" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.customer}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.customer}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form resource="${this.customer}" method="PUT">
        <g:hiddenField name="version" value="${this.customer?.version}"/>
        <fieldset class="form">
            <g:render template="formEdition"/>
        </fieldset>
        <fieldset class="buttons">
            <input class="save" type="submit"
                   value="${message(code: 'default.button.update.label', default: 'Update')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/customer/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'customer.label', default: 'Customer')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>

</head>

<body>
<a href="#list-customer" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                               default="Skip to content&hellip;"/></a>

<g:render template="/layouts/nav"/>

<div id="list-customer" class="content container-fluid scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <sec:ifAnyGranted roles="ROLE_ADMIN,ROLE_VENDEDOR">
        <g:link class="create btn" action="create"><i class="fas fa-plus-circle"></i> <g:message code="default.new.label"
                                                              args="[entityName]"/></g:link>
    </sec:ifAnyGranted>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>


    <div class="">
        <div class="row opciones">
            <br><br><br>
        </div>


        <div class="card">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>Adress</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <g:each in="${customerList}" status="i" var="customerInstance">
                        <tr>
                            <td>
                                ${fieldValue(bean: customerInstance, field: "name")}
                            </td>
                            <td>
                                ${fieldValue(bean: customerInstance, field: "lastName")}
                            </td>
                            <td>
                                <g:link action="show"
                                        id="${customerInstance.id}">${fieldValue(bean: customerInstance, field: "email")}</g:link>
                            </td>
                            <td>
                                ${fieldValue(bean: customerInstance, field: "address")}
                            </td>
                            <td>
                                <g:link action="indexCustomer" controller="orders"
                                        id="${customerInstance.id}">Pedidos</g:link>
                            </td>
                        </tr>
                    </g:each>

                    </tbody>
                </table>

            </div>
        </div>
    </div>

    <g:if test="${customerCount > 0}">
        <div class="pagination">
            <g:paginate total="${customerCount ?: 0}"/>
        </div>
    </g:if>
</div>
</body>
</html>

grails-app/views/customer/show.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'customer.label', default: 'Customer')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<a href="#show-customer" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                               default="Skip to content&hellip;"/></a>

<g:render template="/layouts/nav"/>

<div id="show-customer" class="content scaffold-show" role="main">
    <h1><g:message code="default.show.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
%{-- <f:display bean="customer"/>--}%

    <ol class="property-list dossier">
        <g:if test="${customer?.name}">
            <li class="fieldcontain row"><span id="name-label" class="property-label col-md-6"><g:message
                    code="customer.name.label" default="Name"/></span> <span
                    class="property-value col-md-6" aria-labelledby="email-label"><g:fieldValue bean="${customer}"
                                                                                                field="name"/></span>
            </li>
        </g:if>
        <g:if test="${customer?.lastName}">
            <li class="fieldcontain row"><span id="lastName-label" class="property-label col-md-6"><g:message
                    code="customer.lastName.label" default="Last Name"/></span> <span
                    class="property-value col-md-6" aria-labelledby="email-label"><g:fieldValue bean="${customer}"
                                                                                                field="lastName"/></span>
            </li>
        </g:if>
        <g:if test="${customer?.email}">
            <li class="fieldcontain row"><span id="email-label" class="property-label col-md-6"><g:message
                    code="customer.email.label" default="Email"/></span>
                <span class="property-value col-md-6" aria-labelledby="email-label"><g:fieldValue bean="${customer}"
                                                                                                  field="email"/></span>
            </li>
        </g:if>
        <g:if test="${customer?.gender}">
            <li class="fieldcontain row"><span id="gender-label"
                                               class="property-label col-md-6"><g:message
                        code="dossier.gender.label" default="Genre"/></span> <span
                    class="property-value col-md-6" aria-labelledby="gender-label"><g:message
                        code="${customer?.gender}"/></span></li>
        </g:if>
        <g:if test="${customer?.address}">
            <li class="fieldcontain row"><span id="address-label" class="property-label col-md-6"><g:message
                    code="customer.address.label" default="Address"/></span>
                <span class="property-value col-md-6" aria-labelledby="email-label"><g:fieldValue bean="${customer}"
                                                                                                  field="address"/></span>
            </li>
        </g:if>
        <g:if test="${customer?.cuit}">
            <li class="fieldcontain row"><span id="cuit-label" class="property-label col-md-6"><g:message
                    code="customer.cuit.label" default="Cuit"/></span>
                <span class="property-value col-md-6" aria-labelledby="email-label"><g:fieldValue bean="${customer}"
                                                                                                  field="cuit"/></span>
            </li>
        </g:if>
        <g:if test="${customer?.razonSocial}">
            <li class="fieldcontain row"><span id="razonSocial-label" class="property-label col-md-6"><g:message
                    code="customer.razonSocial.label" default="Razon Cocial"/></span>
                <span class="property-value col-md-6" aria-labelledby="email-label"><g:fieldValue bean="${customer}"
                                                                                                  field="cuit"/></span>
            </li>
        </g:if>
        <g:if test="${customer?.phone}">
            <li class="fieldcontain row"><span id="limiteCompra-label" class="property-label col-md-6"><g:message
                    code="customer.limiteCompra.label" default="Limite de Compra"/></span>
                <span class="property-value col-md-6" aria-labelledby="email-label"><g:fieldValue bean="${customer}"
                                                                                                  field="limiteCompra"/></span>
            </li>
        </g:if>
        <g:if test="${customer?.limiteCompra}">
            <li class="fieldcontain row"><span id="limiteCompra-label" class="property-label col-md-6"><g:message
                    code="customer.phone.label" default="Telefono"/></span>
                <span class="property-value col-md-6" aria-labelledby="email-label"><g:fieldValue bean="${customer}"
                                                                                                  field="phone"/></span>
            </li>
        </g:if>


        <g:form resource="${this.customer}" method="DELETE">
            <fieldset class="buttons">
                <sec:ifAnyGranted roles="ROLE_ADMIN,ROLE_VENDEDOR,ROLE_CLIENTE ">
                    <g:link class="edit" action="edit" resource="${this.customer}"><g:message
                            code="default.button.edit.label" default="Edit"/></g:link>
                </sec:ifAnyGranted>
                <sec:ifAnyGranted roles="ROLE_ADMIN">
                    <input class="delete" type="submit"
                           value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                           onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>

                </sec:ifAnyGranted>
            </fieldset>
        </g:form>
</div>
</body>
</html>