grails-app/domain/com/changeIT/ResumenPedido.groovy
package com.changeIT

class ResumenPedido {

    Product productoOrdenado
    int cantidad


    static constraints = {
    }
}

grails-app/controllers/com/changeIT/ResumenPedidoController.groovy
package com.changeIT

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class ResumenPedidoController {

    ResumenPedidoService resumenPedidoService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    @Secured(['ROLE_ADMIN', 'ROLE_VENDEDOR', 'ROLE_CLIENTE'])
    def index(String id) {
         respond Orders.findByCodigoPedido(id).getResumenPedidos(), model:[resumenPedidoCount: Orders.findByCodigoPedido(id).getResumenPedidos().size()]
    }
    @Secured(['ROLE_ADMIN', 'ROLE_VENDEDOR', 'ROLE_CLIENTE'])
    def show(Long id) {
        respond resumenPedidoService.get(id)
    }
    @Secured(['ROLE_ADMIN', 'ROLE_VENDEDOR', 'ROLE_CLIENTE'])
    def create() {
        respond new ResumenPedido(params)
    }
    @Secured(['ROLE_ADMIN', 'ROLE_VENDEDOR', 'ROLE_CLIENTE'])
    def save(ResumenPedido resumenPedido) {
        if (resumenPedido == null) {
            notFound()
            return
        }

        try {
            resumenPedidoService.save(resumenPedido)
        } catch (ValidationException e) {
            respond resumenPedido.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'resumenPedido.label', default: 'ResumenPedido'), resumenPedido.id])
                redirect resumenPedido
            }
            '*' { respond resumenPedido, [status: CREATED] }
        }
    }
    @Secured(['ROLE_ADMIN', 'ROLE_VENDEDOR', 'ROLE_CLIENTE'])
    def edit(Long id) {
        respond resumenPedidoService.get(id)
    }
    @Secured(['ROLE_ADMIN', 'ROLE_VENDEDOR', 'ROLE_CLIENTE'])
    def update(ResumenPedido resumenPedido) {
        if (resumenPedido == null) {
            notFound()
            return
        }

        try {
            resumenPedidoService.save(resumenPedido)
        } catch (ValidationException e) {
            respond resumenPedido.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'resumenPedido.label', default: 'ResumenPedido'), resumenPedido.id])
                redirect resumenPedido
            }
            '*'{ respond resumenPedido, [status: OK] }
        }
    }
    @Secured(['ROLE_ADMIN', 'ROLE_VENDEDOR', 'ROLE_CLIENTE'])
    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        resumenPedidoService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'resumenPedido.label', default: 'ResumenPedido'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'resumenPedido.label', default: 'ResumenPedido'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/resumenPedido/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'resumenPedido.label', default: 'ResumenPedido')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-resumenPedido" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-resumenPedido" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.resumenPedido}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.resumenPedido}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.resumenPedido}" method="POST">
                <fieldset class="form">
                    <f:all bean="resumenPedido"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/resumenPedido/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'resumenPedido.label', default: 'ResumenPedido')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-resumenPedido" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-resumenPedido" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.resumenPedido}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.resumenPedido}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.resumenPedido}" method="PUT">
                <g:hiddenField name="version" value="${this.resumenPedido?.version}" />
                <fieldset class="form">
                    <f:all bean="resumenPedido"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/resumenPedido/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'resumenPedido.label', default: 'ResumenPedido')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-resumenPedido" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                    default="Skip to content&hellip;"/></a>

<g:render template="/layouts/nav"/>

<div id="list-resumenPedido" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>

    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>

    <div class="card">
        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Producto</th>
                    <th>Cantidad</th>

                </thead>
                <tbody>
                <g:each in="${resumenPedidoList}" status="i" var="resumeInstance">
                    <tr>
                        <td>
                            <g:link action="show" controller="product"
                                    id="${resumeInstance?.productoOrdenado.id}">${fieldValue(bean: resumeInstance?.productoOrdenado, field: "articulo")}</g:link>
                        </td>
                        <td>
                            ${fieldValue(bean: resumeInstance, field: "cantidad")}
                        </td>

                    </tr>
                </g:each>

                </tbody>
            </table>

        </div>
    </div>



</div>
</body>
</html>

grails-app/views/resumenPedido/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'resumenPedido.label', default: 'ResumenPedido')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-resumenPedido" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-resumenPedido" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="resumenPedido" />
            <g:form resource="${this.resumenPedido}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.resumenPedido}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>