grails-app/domain/com/changeIT/SecUser.groovy
package com.changeIT

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString
import grails.compiler.GrailsCompileStatic
import groovy.util.logging.Slf4j


@Slf4j
@GrailsCompileStatic
@EqualsAndHashCode(includes = 'username')
@ToString(includes = 'username', includeNames = true, includePackage = false)
class SecUser implements Serializable {
    transient springSecurityService
    private static final long serialVersionUID = 1

    String username
    String password
    boolean enabled = true
    boolean accountExpired
    boolean accountLocked
    boolean passwordExpired
    String name
    String lastName
    String phone
    String email
    Integer attempts

    Set<SecRole> getAuthorities() {
        (SecUserSecRole.findAllBySecUser(this) as List<SecUserSecRole>)*.secRole as Set<SecRole>
    }

    static constraints = {
        username nullable: false, blank: false, unique: true
        password blank: false, validator: { value ->
            Boolean hasMayus = (value =~ /\p{Upper}/).find()
            Boolean hasMinus = (value =~ /\p{Lower}/).find()
            Boolean hasSymbol = (value =~ /\p{Punct}/).find()
            Boolean hasNumber = (value =~ /\d/).find()
            (hasMayus && hasMinus && hasSymbol && hasNumber ) ?: 'format.error'
        }
        password minSize: 8
        name(nullable: true)
        lastName(nullable: true)
        phone(nullable: true)
        email(unique: false)

    }

    static mapping = {
        autowire true
        password column: '`password`'
    }



}

grails-app/controllers/com/changeIT/SecUserController.groovy
package com.changeIT

import com.changeIT.util.Util
import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*
import grails.plugin.htmlcleaner.HtmlCleaner

class SecUserController {
    HtmlCleaner htmlCleaner
    SecUserService secUserService
    SecUserSecRoleService secUserSecRoleService
    SecUserCustomService secUserCustomService
    CorreoUtil correo = new CorreoUtil()
    Util util = new Util()

    static allowedMethods = [index : ['GET'], create: ['GET'], show: ['GET'], edit: ['GET'],
                             update: ['POST'], save: ['POST'], delete: ['POST']]

    @Secured(['ROLE_ADMIN'])
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond secUserService.list(params), model: [secUserCount: secUserService.count()]
    }

    @Secured(['ROLE_ADMIN'])
    def show(Long id) {
        SecUser secUserInstance = SecUser.get(id)
        if (!secUserInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'secUser.label', default: 'SecUser'), id])
            redirect(action: "list")
            return
        }

        SecUserSecRole secUserSecRole = SecUserSecRole.findBySecUser(secUserInstance)

        [secUserInstance: secUserInstance, role: secUserSecRole.secRole]
    }

    @Secured(['ROLE_ADMIN'])
    def create() {
        [secUserInstance: chainModel?.secUserInstance ?: new SecUser(params), rolesInstance: SecRole.list()]
    }

    @Secured(['ROLE_ADMIN'])
    def save(SecUser secUser) {
        if (secUser == null) {
            notFound()
            return
        }

        try {
            SecUser user = new SecUser(username: htmlCleaner.cleanHtml(params.username, 'none'), password: params.password, enabled: params.enabled != null ? true : false, accountExpired: params.accountExpired != null ? true : false, accountLocked: params.accountLocked != null ? true : false, passwordExpired: params.passwordExpired != null ? true : false, name:  htmlCleaner.cleanHtml(params.name, 'none'), lastName: htmlCleaner.cleanHtml(params.lastName, 'none'), phone: htmlCleaner.cleanHtml(params.phone, 'none'), email: htmlCleaner.cleanHtml(params.email, 'none'),attempts: 0)

            secUserService.save(user)
            SecRole secRole = SecRole.get(params.roles)
            SecUserSecRole userRole = new SecUserSecRole(secUser: user, secRole: secRole)
            secUserSecRoleService.save(userRole)

            String MAIL_TEMPLATES = "mail"
            String text = util.getFile(MAIL_TEMPLATES + File.separator + "userPassInform.html")
            text = text.replace("[password]", htmlCleaner.cleanHtml(params.password, 'none'))
            text = text.replace("[email]", user.getEmail())
            text = text.replace("[title]", g.message(code: "mail.tarificador.title"))
            text = text.replace("[text]", g.message(code: "mail.user.create.text"))
            text = text.replace("[text2]", g.message(code: "mail.user.create.text2"))
            text = text.replace("[text3]", g.message(code: "mail.user.create.text3"))
            text = text.replace("[text4]", g.message(code: "mail.user.create.text4"))
            text = text.replace("[greeting]", g.message(code: "mail.greeting"))
            correo.sendMail(text, g.message(code: "mail.user.subject.update"), user.getEmail())

            redirect(action: "show", id: user.id)
        } catch (ValidationException e) {
            respond secUser.errors, view: 'create'
            return
        }


    }

    @Secured(['ROLE_ADMIN'])
    def edit(Long id) {
        def secUserInstance = SecUser.get(id)

        try {

            if (!secUserInstance) {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'secUser.label', default: 'SecUser'), id])
                redirect(action: "list")
                return
            }

            def roleMap = [:]
            def allRoles = []
            def roles = SecRole.list()
            def userRoles = SecUserSecRole.findBySecUser(secUserInstance)
            def selectedRoles = []

            roles.each { it ->
                allRoles << it
            }

            userRoles.each { it ->
                selectedRoles << it.secRole
            }

            for (int i = 0; i < allRoles.size(); i++) {

                if (secUserCustomService.isSelected(allRoles.get(i), selectedRoles)) {
                    roleMap.put(allRoles.get(i), true)
                } else {
                    roleMap.put(allRoles.get(i), false)
                }

            }

            [secUserInstance: secUserInstance, roleMap: roleMap]


        } catch (Exception e) {
            redirect(controller: "exception", action: "generalException", params: [message: "There was an error while calling method edit() from SecUserController", e: e, cont: "secUser", act: "list"])
        }
    }

    @Secured(['ROLE_ADMIN'])
    def update(Long id, Long version) {
        String MAIL_TEMPLATES = "mail"
        def secUserInstance = SecUser.get(id)
        String text = util.getFile(MAIL_TEMPLATES + File.separator + "userPassInform.html")
        withForm {
            try {
                def username = htmlCleaner.cleanHtml(params.username, 'none')
                def password = params.password
                def enabled = params.enabled != null ? true : false
                def passwordExpired = params.passwordExpired != null ? true : false
                def accountExpired = params.accountExpired != null ? true : false
                def accountLocked = params.accountLocked != null ? true : false
                def selectedRole = params.role
                def email = params.email
                def name = htmlCleaner.cleanHtml(params.name, 'none')
                def lastName = htmlCleaner.cleanHtml(params.lastName, 'none')
                def phone = htmlCleaner.cleanHtml(params.phone, 'none')

                secUserInstance.setUsername(username)

                secUserInstance.setPassword(password)
                secUserInstance.setEnabled(enabled)
                secUserInstance.setPasswordExpired(passwordExpired)
                secUserInstance.setAccountExpired(accountExpired)
                secUserInstance.setAccountLocked(accountLocked)

                secUserInstance.setEmail(email)
                secUserInstance.setName(name)
                secUserInstance.setLastName(lastName)
                secUserInstance.setPhone(phone)
                secUserInstance.setAttempts(0)

                def role = SecRole.get(selectedRole)

                SecUserSecRole.removeAll(secUserInstance)

                if (!secUserInstance.save(flush: true)) {
                    render(view: "edit", model: [secUserInstance: secUserInstance])
                    return
                }

                SecUserSecRole userRole = new SecUserSecRole(secUser: secUserInstance, secRole: role)
                userRole.save(flush: true)

                text = text.replace("[password]", htmlCleaner.cleanHtml(password, 'none'))
                text = text.replace("[email]", email)
                text = text.replace("[title]", g.message(code: "mail.tarificador.title"))
                text = text.replace("[text]", g.message(code: "mail.user.create.text"))
                text = text.replace("[text2]", g.message(code: "mail.user.create.text2"))
                text = text.replace("[text3]", g.message(code: "mail.user.create.text3"))
                text = text.replace("[text4]", g.message(code: "mail.user.create.text4"))
                text = text.replace("[greeting]", g.message(code: "mail.greeting"))
                correo.sendMail(text, g.message(code: "mail.user.subject.update"), email)
                flash.message = message(code: 'default.updated.message', args: [message(code: 'secUser.label', default: 'SecUser'), secUserInstance.id])
                redirect(action: "show", id: secUserInstance.id)
            } catch (Exception e) {
                redirect(controller: "exception", action: "generalException", params: [message: "There was an error while calling method update() from SecUserController", e: e.getMessage(), cont: "secUser", act: "list"])
            }
        }.invalidToken {
            // bad request
        }


    }

    @Secured(['ROLE_ADMIN'])
    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        secUserService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'secUser.label', default: 'SecUser'), id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    @Secured(['ROLE_ADMIN'])
    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'secUser.label', default: 'SecUser'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/secUser/_form.gsp
<%@ page import="com.changeIT.SecUser" %>
<div class="row">
    <div class="col-md-6">
        <div class="fieldcontain row ${hasErrors(bean: secUserInstance, field: 'username', 'error')} required">
            <label for="username" class="col-md-4"><g:message code="secuser.form.user" default="User"/>
                <span class="required-indicator">*</span>
            </label>

            <div class="col-md-8">
                <g:textField name="username" required=""
                             value="${secUserInstance?.username}" class="form-control"/>
            </div>
        </div>

        <div class="fieldcontain row ${hasErrors(bean: secUserInstance, field: 'password', 'error')} required">
            <label for="password" class="col-md-4"><g:message code="secuser.form.password" default="Password"/>
                <span class="required-indicator">*</span>
            </label>

            <div class="col-md-8">
                <g:passwordField name="password"  required=""  class="form-control"/>
            </div>

        </div>

        <div class="fieldcontain row ${hasErrors(bean: secUserInstance, field: 'name', 'error')} required">
            <label for="name" class="col-md-4"><g:message code="secuser.form.name" default="Name"/>
            </label>

            <div class="col-md-8">


                <g:textField name="name" required="" value="${secUserInstance?.name}" class="form-control"/>
            </div>
        </div>


        <div
                class="fieldcontain row ${hasErrors(bean: secUserInstance, field: 'lastName', 'error')} required">
            <label for="lastName" class="col-md-4"><g:message
                    code="secuser.form.lastName"
                    default="Last Name"/>
            </label>

            <div class="col-md-8">

            <g:textField name="lastName" required=""
                         value="${secUserInstance?.lastName}" class="form-control"/>

            </div>

        </div>

        <div
                class="fieldcontain row ${hasErrors(bean: secUserInstance, field: 'email', 'error')} required">
            <label for="email" class="col-md-4"><g:message
                    code="secuser.form.email"
                    default="Email"/>
            </label>
            <div class="col-md-8">
            <g:textField name="email" required=""
                         value="${secUserInstance?.email}" class="form-control"/>
            </div>
        </div>

        <div
                class="fieldcontain row ${hasErrors(bean: secUserInstance, field: 'phone', 'error')} required">
            <label for="phone" class="col-md-4"><g:message
                    code="secuser.form.phone"
                    default="Phone"/>
            </label>
            <div class="col-md-8">
            <g:textField name="phone" required=""
                         value="${secUserInstance?.phone}" class="form-control"/>

            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div
                class="form-group fieldcontain ${hasErrors(bean: secUserInstance, field: 'enabled', 'error')}">
            <label class="check-box-label container" for="accountLocked"><g:message
                    code="secuser.form.enable"
                    default="Enabled"/>
            <g:checkBox name="enabled"
                        value="${secUserInstance?.enabled}"/>
                <span class="checkmark"></span>
            </label>

        </div>

        <div
                class="form-group fieldcontain ${hasErrors(bean: secUserInstance, field: 'accountLocked', 'error')} required">
            <label class="check-box-label container" for="accountLocked"><g:message
                    code="secuser.form.accountLocked"
                    default="Account locked"/>

            <g:checkBox name="accountLocked"
                        value="${secUserInstance?.accountLocked}"/>
                <span class="checkmark"></span>
            </label>
        </div>

        <div
                class="form-group fieldcontain ${hasErrors(bean: secUserInstance, field: 'passwordExpired', 'error')} required">
            <label class="check-box-label container" for="passwordExpired"><g:message
                    code="secuser.form.passwordExpired"
                    default="Password expired"/>
            <g:checkBox name="passwordExpired"
                        value="${secUserInstance?.passwordExpired}"/>
                <span class="checkmark"></span>
            </label>

        </div>

        <div
                class="form-group fieldcontain ${hasErrors(bean: secUserInstance, field: 'accountExpired', 'error')} required">
            <label class="check-box-label container" for="accountExpired"><g:message
                    code="secuser.form.accountExpired"
                    default="Account expired"/>
            <g:checkBox name="accountExpired"
                        value="${secUserInstance?.accountExpired}"/>
                <span class="checkmark"></span>
            </label>

        </div>

    </div>

    <div class="col-md-3">

        <g:each in="${roleMap}" var="role" status="i">
            <div class="fieldcontain form-group">

                <label class="check-box-label container"><g:message
                        code="secUserInstance.role.label"
                        default="${role.key.authority}"/>

                <g:radio name="role" value="${role.key.id}"
                         checked="${role.value}"/>
                    <span class="checkmark radio"></span>

                </label>
            </div>
        </g:each>
    </div>
</div>

grails-app/views/secUser/_resultsTable.gsp
<div class="table-responsive">
    <table id="resultsTable" class="table">
        <thead>
        <tr>
            <th data-hql-path="secUser.username" onclick="onClickTableHeader(this)"><g:message
                    code="secuser.form.user"/></th>
            <th data-hql-path="secUser.enabled" onclick="onClickTableHeader(this)"><g:message
                    code="secuser.form.enable"/></th>
            <th data-hql-path="secUser.accountExpired" onclick="onClickTableHeader(this)"><g:message
                    code="secuser.form.accountExpired"/></th>
            <th data-hql-path="secUser.accountLocked" onclick="onClickTableHeader(this)"><g:message
                    code="secuser.form.accountLocked"/></th>
            <th data-hql-path="secUser.passwordExpired" onclick="onClickTableHeader(this)"><g:message
                    code="secuser.form.passwordExpired"/></th>

        </tr>
        </thead>
        <tbody>
        <g:each in="${secUserList}" status="i" var="secUserInstance">
            <tr>
                <td><g:link action="show"
                            id="${secUserInstance.id}">${fieldValue(bean: secUserInstance, field: "username")}</g:link></td>
                <td>${fieldValue(bean: secUserInstance, field: "enabled")}</td>
                <td>${fieldValue(bean: secUserInstance, field: "accountExpired")}</td>
                <td>${fieldValue(bean: secUserInstance, field: "accountLocked")}</td>
                <td>${fieldValue(bean: secUserInstance, field: "accountExpired")}</td>
            </tr>
        </g:each>
        </tbody>
    </table>
</div>
<g:hiddenField name="total" value="${secUserInstanceTotal}"/>
<g:hiddenField name="offset" value="${offset}"/>
<g:hiddenField name="orderBy" value="${orderBy}"/>
<g:hiddenField name="orderMode" value="${orderMode}"/>

grails-app/views/secUser/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'secUser.label', default: 'SecUser')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-secUser" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
    <g:render template="/layouts/nav"/>
        <div id="create-secUser" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.secUser}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.secUser}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form useToken="${true}" action="save">
                <fieldset class="form">

                    <div class="row">
                        <div class="col-md-6">
                            <div
                                    class="form-group row fieldcontain ${hasErrors(bean: secUserInstance, field: 'username', 'error')} required">
                                <label class="col-md-5" for=username> <g:message
                                        code="secuser.create.user" default="User" /> <span
                                        class="required-indicator">*</span>
                                </label>
                                <div class="col-md-7">
                                    <g:textField name="username" required=""
                                                 value="${secUserInstance?.username}" class="form-control" />
                                </div>
                            </div>
                            <div
                                    class="form-group row fieldcontain ${hasErrors(bean: secUserInstance, field: 'password', 'error')} required">
                                <label class="col-md-5 " for=password> <g:message
                                        code="secuser.create.password" default="Password" /> <span
                                        class="required-indicator">*</span>
                                </label>
                                <div class="col-md-7">
                                    <g:textField name="password" required=""
                                                 value="${secUserInstance?.password}" class="form-control"/>
                                </div>
                            </div>
                            <div
                                    class="form-group row fieldcontain ${hasErrors(bean: secUserInstance, field: 'name', 'error')} required">
                                <label for="name" class="col-md-5 col-form-label"> <g:message
                                        code="secuser.create.name" default="Nom" /> <span
                                        class="required-indicator">*</span>
                                </label>
                                <div class="col-md-7">
                                    <g:textField name="name" required=""
                                                 value="${secUserInstance?.name}" class="form-control"/>
                                </div>
                            </div>
                            <div
                                    class="form-group row fieldcontain ${hasErrors(bean: secUserInstance, field: 'lastName', 'error')} required">
                                <label for="lastName" class="col-md-5 col-form-label"> <g:message
                                        code="secuser.create.lastName"  /> <span
                                        class="required-indicator">*</span>
                                </label>
                                <div class="col-md-7">
                                    <g:textField name="lastName" required=""
                                                 value="${secUserInstance?.lastName}" class="form-control" />
                                </div>
                            </div>
                            <div
                                    class="form-group row fieldcontain ${hasErrors(bean: secUserInstance, field: 'email', 'error')} required">
                                <label for="email" class="col-md-5 col-form-label"> <g:message
                                        code="secuser.create.email" default="Email" /> <span
                                        class="required-indicator">*</span>
                                </label>
                                <div class="col-md-7">
                                    <g:textField name="email" required=""
                                                 value="${secUserInstance?.email}" class="form-control" />
                                </div>
                            </div>
                            <div
                                    class="form-group row fieldcontain ${hasErrors(bean: secUserInstance, field: 'phone', 'error')} required">
                                <label for="phone"  class="col-md-5 col-form-label"> <g:message
                                        code="secuser.create.phone" default="Téléphone portable" />
                                    <span class="required-indicator">*</span>
                                </label>
                                <div class="col-md-7">
                                    <g:textField name="phone" required=""
                                                 value="${secUserInstance?.phone}" class="form-control"/>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-md-6">
                                    <div
                                            class="form-group fieldcontain ${hasErrors(bean: secUserInstance, field: 'enabled', 'error')} required">
                                        <label class="check-box-label container" for="enabled"> <g:message
                                                code="secuser.create.enable"
                                                default="Enabled" /> <span
                                                class="required-indicator"></span>
                                            <g:checkBox name="enabled"
                                                        value="${secUserInstance?.enabled}" />
                                            <span class="checkmark"></span>

                                        </label>

                                    </div>
                                    <div
                                            class="form-group fieldcontain  ${hasErrors(bean: secUserInstance, field: 'accountExpired', 'error')} required">

                                        <label class="check-box-label container" for="accountExpired"> <g:message
                                                code="secuser.create.accountExpired"
                                                default="Account Expired" /> <span
                                                class="required-indicator"></span>
                                            <g:checkBox name="accountExpired"
                                                        value="${secUserInstance?.accountExpired}" />
                                            <span class="checkmark"></span>
                                        </label>

                                    </div>
                                    <div
                                            class="form-group fieldcontain ${hasErrors(bean: secUserInstance, field: 'accountLocked', 'error')} required">

                                        <label class="check-box-label container" for="accountLocked"> <g:message
                                                code="secuser.create.accountLocked"
                                                default="Locked" /> <span
                                                class="required-indicator"></span>

                                            <g:checkBox name="accountLocked"
                                                        value="${secUserInstance?.accountLocked}" />

                                            <span class="checkmark"></span>
                                        </label>

                                    </div>

                                    <div
                                            class="form-group fieldcontain ${hasErrors(bean: secUserInstance, field: 'passwordExpired', 'error')} required">

                                        <label class="check-box-label container" for="passwordExpired"> <g:message
                                                code="secuser.create.passwordExpired"
                                                default="Password Expired" /> <span
                                                class="required-indicator"></span>
                                            <g:checkBox name="passwordExpired"
                                                        value="${secUserInstance?.passwordExpired}" />
                                            <span class="checkmark"></span>
                                        </label>

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <g:each in="${rolesInstance}" var="role" status="i">
                                        <div class="fieldcontain form-group">
                                            <label class="check-box-label container">

                                                <g:message code="dossier.customer.phone.label2" default="${role.authority}" />
                                                <g:radio name="roles" value="${role.id}" checked="false" />
                                                <span class="checkmark radio"></span>
                                            </label>
                                        </div>
                                    </g:each>
                                </div>

                            </div>


                        </div>
                    </div>




                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="btn btn-save"
                                    value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>








        </div>
    </body>
</html>

grails-app/views/secUser/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'secUser.label', default: 'SecUser')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-secUser" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
    <g:render template="/layouts/nav"/>
        <div id="edit-secUser" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.secUser}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.secUser}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form useToken="${true}"action="update" method="post" class="form-explorer">
                <g:hiddenField name="id" value="${secUserInstance?.id}" />
                <g:hiddenField name="version" value="${secUserInstance?.version}" />
                <g:render template="form"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:actionSubmit class="btn btn-save" action="update" value="${message(code: 'secuser.edit.update', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>